FROM local/build-essential
WORKDIR /tmp
RUN \
 wget http://www.udpxy.com/download/1_23/udpxy.1.0.23-9-prod.tar.gz && \
 tar -xzvf udpxy.1.0.23-9-prod.tar.gz && \
 cd udpxy-1.0.23-9 && \
 make CFLAGS='-static' && \
 make install
